#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage:  init <filename>"
  exit 62
fi

BANK_FILE="$1.bank"
ATM_FILE="$1.atm"

if test -f "$BANK_FILE" || test -f "$ATM_FILE";
then
  echo "Error: one of the files already exists"
  exit 63
fi

if (touch "$BANK_FILE" && touch "$ATM_FILE");
then
  echo "Successfully initialized bank state"
  SECRET=$(openssl rand -hex 256)
  SECRET2=$(openssl rand -hex 256)
  echo $SECRET >> "$ATM_FILE"
  echo $SECRET >> "$BANK_FILE"
  echo $SECRET2 >> "$ATM_FILE"
  echo $SECRET2 >> "$BANK_FILE"
  exit 0
else
  echo "Error creating initialization files"
  exit 64
fi

