#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage:  init <filename>"
  exit 62
fi

BANK_FILE="$1.bank"
ATM_FILE="$1.atm"

if test -f "$BANK_FILE" || test -f "$ATM_FILE";
then
  echo "Error: one of the files already exists"
  exit 63
fi

gen_aes_key () {
  openssl enc -aes-256-cbc -pass pass:key1 -P -pbkdf2 -iter 10000 | sed '1d' | sed 's/.*key=//' | sed 's/.*iv =//'
}

if (touch "$BANK_FILE" && touch "$ATM_FILE");
then
  CARD_KEY=$(gen_aes_key)
  COMM_KEY=$(gen_aes_key)
  echo "$CARD_KEY" >> $ATM_FILE
  echo "$CARD_KEY" >> $BANK_FILE
  echo "$COMM_KEY" >> $ATM_FILE
  echo "$COMM_KEY" >> $BANK_FILE
  echo "Successfully initialized bank state"
  exit 0
else
  echo "Error creating initialization files"
  exit 64
fi

